version: "3"

services:
  swagger-integrated-proto:
    image: swaggerapi/swagger-ui
    container_name: swagger-integrated-proto
    ports:
      - "2999:8080"
    restart: on-failure
    environment:
      - URLS=
        [
        {url:'http://localhost:8080/docs/openapi3.sample-springboot-restdocs.json',name:'Test'},
        {url:'http://localhost:8000/docs/openapi3.sample-fastapi.json',name:'My Subproject A'},
        {url:'http://localhost:5000/docs/openapi3.sample-express.json',name:'My Subproject B'}
        ]
